Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/conda/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/conda/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/conda/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/conda/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/opt/conda/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/conda/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from ekorpkit import eKonf

df_cfg = eKonf.compose(config_group='pipeline=blank')
df_cfg.name = 'edgar_sample'
df_cfg.data_dir = "${cached_path:'gd://15WFOGe73pIDvJEJxV90luirsT4yEInz9:edgar.zip',true,true}"
df_cfg.data_file = 'edgar.parquet'
df_cfg.columns_to_keep = ['id', 'filename', 'item', 'cik', 'company', 'text']
df = eKonf.instantiate(df_cfg)
df.head()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m/opt/conda/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py[0m in [0;36m_call_target[0;34m(_target_, _partial_, args, kwargs, full_key)[0m
[1;32m     85[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 86[0;31m             [0;32mreturn[0m [0m_target_[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     87[0m         [0;32mexcept[0m [0mException[0m [0;32mas[0m [0me[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/workspace/projects/ekorpkit/ekorpkit/pipelines/pipe.py[0m in [0;36mpipeline[0;34m(**cfg)[0m
[1;32m   1491[0m     [0;32melif[0m [0mdata_dir[0m [0;32mand[0m [0mdata_file[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1492[0;31m         [0mdf[0m [0;34m=[0m [0m_load_dataframe[0m[0;34m([0m[0mdf[0m[0;34m,[0m [0margs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1493[0m [0;34m[0m[0m

[0;32m/workspace/projects/ekorpkit/ekorpkit/pipelines/pipe.py[0m in [0;36m_load_dataframe[0;34m(df, args)[0m
[1;32m   1394[0m         [0;32mif[0m [0mconcatenate[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1395[0;31m             df = pd.concat(
[0m[1;32m   1396[0m                 [

[0;32m/opt/conda/lib/python3.8/site-packages/pandas/core/reshape/concat.py[0m in [0;36mconcat[0;34m(objs, axis, join, ignore_index, keys, levels, names, verify_integrity, sort, copy)[0m
[1;32m    273[0m     """
[0;32m--> 274[0;31m     op = _Concatenator(
[0m[1;32m    275[0m         [0mobjs[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/conda/lib/python3.8/site-packages/pandas/core/reshape/concat.py[0m in [0;36m__init__[0;34m(self, objs, axis, join, keys, levels, names, ignore_index, verify_integrity, copy, sort)[0m
[1;32m    330[0m         [0;32mif[0m [0mlen[0m[0;34m([0m[0mobjs[0m[0;34m)[0m [0;34m==[0m [0;36m0[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 331[0;31m             [0;32mraise[0m [0mValueError[0m[0;34m([0m[0;34m"No objects to concatenate"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    332[0m [0;34m[0m[0m

[0;31mValueError[0m: No objects to concatenate

The above exception was the direct cause of the following exception:

[0;31mInstantiationException[0m                    Traceback (most recent call last)
[0;32m<ipython-input-2-3b8cbbfbfda1>[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m [0mdf_cfg[0m[0;34m.[0m[0mdata_file[0m [0;34m=[0m [0;34m'edgar.parquet'[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0mdf_cfg[0m[0;34m.[0m[0mcolumns_to_keep[0m [0;34m=[0m [0;34m[[0m[0;34m'id'[0m[0;34m,[0m [0;34m'filename'[0m[0;34m,[0m [0;34m'item'[0m[0;34m,[0m [0;34m'cik'[0m[0;34m,[0m [0;34m'company'[0m[0;34m,[0m [0;34m'text'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 8[0;31m [0mdf[0m [0;34m=[0m [0meKonf[0m[0;34m.[0m[0minstantiate[0m[0;34m([0m[0mdf_cfg[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      9[0m [0mdf[0m[0;34m.[0m[0mhead[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/workspace/projects/ekorpkit/ekorpkit/ekonf.py[0m in [0;36minstantiate[0;34m(config, *args, **kwargs)[0m
[1;32m    507[0m     [0;34m@[0m[0mstaticmethod[0m[0;34m[0m[0;34m[0m[0m
[1;32m    508[0m     [0;32mdef[0m [0minstantiate[0m[0;34m([0m[0mconfig[0m[0;34m:[0m [0mAny[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m:[0m [0mAny[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m:[0m [0mAny[0m[0;34m)[0m [0;34m->[0m [0mAny[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 509[0;31m         [0;32mreturn[0m [0m_instantiate[0m[0;34m([0m[0mconfig[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    510[0m [0;34m[0m[0m
[1;32m    511[0m     [0;34m@[0m[0mstaticmethod[0m[0;34m[0m[0;34m[0m[0m

[0;32m/workspace/projects/ekorpkit/ekorpkit/ekonf.py[0m in [0;36m_instantiate[0;34m(config, *args, **kwargs)[0m
[1;32m    343[0m     [0;32mif[0m [0m_Keys[0m[0;34m.[0m[0mRECURSIVE[0m [0;32mnot[0m [0;32min[0m [0mkwargs[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    344[0m         [0mkwargs[0m[0;34m[[0m[0m_Keys[0m[0;34m.[0m[0mRECURSIVE[0m[0;34m][0m [0;34m=[0m [0m_recursive_[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 345[0;31m     [0;32mreturn[0m [0mhydra[0m[0;34m.[0m[0mutils[0m[0;34m.[0m[0minstantiate[0m[0;34m([0m[0mconfig[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    346[0m [0;34m[0m[0m
[1;32m    347[0m [0;34m[0m[0m

[0;32m/opt/conda/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py[0m in [0;36minstantiate[0;34m(config, *args, **kwargs)[0m
[1;32m    216[0m         [0m_partial_[0m [0;34m=[0m [0mconfig[0m[0;34m.[0m[0mpop[0m[0;34m([0m[0m_Keys[0m[0;34m.[0m[0mPARTIAL[0m[0;34m,[0m [0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    217[0m [0;34m[0m[0m
[0;32m--> 218[0;31m         return instantiate_node(
[0m[1;32m    219[0m             [0mconfig[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0mrecursive[0m[0;34m=[0m[0m_recursive_[0m[0;34m,[0m [0mconvert[0m[0;34m=[0m[0m_convert_[0m[0;34m,[0m [0mpartial[0m[0;34m=[0m[0m_partial_[0m[0;34m[0m[0;34m[0m[0m
[1;32m    220[0m         )

[0;32m/opt/conda/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py[0m in [0;36minstantiate_node[0;34m(node, convert, recursive, partial, *args)[0m
[1;32m    329[0m                     [0mkwargs[0m[0;34m[[0m[0mkey[0m[0;34m][0m [0;34m=[0m [0m_convert_node[0m[0;34m([0m[0mvalue[0m[0;34m,[0m [0mconvert[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    330[0m [0;34m[0m[0m
[0;32m--> 331[0;31m             [0;32mreturn[0m [0m_call_target[0m[0;34m([0m[0m_target_[0m[0;34m,[0m [0mpartial[0m[0;34m,[0m [0margs[0m[0;34m,[0m [0mkwargs[0m[0;34m,[0m [0mfull_key[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    332[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    333[0m             [0;31m# If ALL or PARTIAL non structured, instantiate in dict and resolve interpolations eagerly.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/conda/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py[0m in [0;36m_call_target[0;34m(_target_, _partial_, args, kwargs, full_key)[0m
[1;32m     89[0m             [0;32mif[0m [0mfull_key[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     90[0m                 [0mmsg[0m [0;34m+=[0m [0;34mf"\nfull_key: {full_key}"[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 91[0;31m             [0;32mraise[0m [0mInstantiationException[0m[0;34m([0m[0mmsg[0m[0;34m)[0m [0;32mfrom[0m [0me[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     92[0m [0;34m[0m[0m
[1;32m     93[0m [0;34m[0m[0m

[0;31mInstantiationException[0m: Error in call to target 'ekorpkit.pipelines.pipe.pipeline':
ValueError('No objects to concatenate')
full_key: pipeline
InstantiationException: Error in call to target 'ekorpkit.pipelines.pipe.pipeline':
ValueError('No objects to concatenate')
full_key: pipeline

